### ISSUE TITLE
Add the OpenRAIL++ License as an option for models

### ISSUE THREAD

**Issue by ProGamerGov** [huggingface/hub-docs#490] opened 2022-11-09 16:33 UTC
**Is your feature request related to a problem? Please describe.**

The current OpenRAIL license family contains some very problematic lines that allow for forced updates and restrictions of models.

> Updates and Runtime Restrictions. To the maximum extent permitted by law, Licensor reserves the right to restrict (remotely or otherwise) usage of the Model in violation of this License, update the Model through electronic means, or modify the Output of the Model based on updates. **You shall undertake reasonable efforts to use the latest version of the Model**. 

This means that users are not supposed to ever be using previous versions of models, which is very problematic and dangerous.

**Describe the solution you'd like**

The OpenRAIL++ License removes these dangerous lines.

Source: https://www.ykilcher.com/license

**Describe alternatives you've considered**

There aren't any alternatives.

**Additional context**

A video on the subject was made here: https://www.youtube.com/watch?v=W5M-dvzpzSQ

**Comment by julien-c** [comment] 2022-11-14 12:27
For @annatrdj and @CarlosMFerr

**Comment by julien-c** [comment] 2022-11-14 12:45
Yes i think we should add it as a built-in option

**Comment by julien-c** [comment] 2022-11-14 12:45
cc @yk too

**Comment by meg-huggingface** [comment] 2022-11-14 16:26
I agree that this would be a useful change, but see the "++" designation in the name is problematic. 
Suggest using another name that is not tied to the ++ denotation in computer science.

**Comment by meg-huggingface** [comment] 2022-11-14 18:40
I have no additional points to make at this time; please everyone feel free to consider other names.
Technically, if we remove a clause and want to stick with CS denotation, OpenRail-- may be more appropriate.

**Comment by julien-c** [comment] 2022-11-14 18:42
`++` implies it's an improved version (and even though C was better than C++)

maybe a more explicit `openrail-no-updates-required` would be better?

**Comment by julien-c** [comment] 2022-11-14 18:43
or OpenRAIL--

**Comment by yk** [comment] 2022-11-14 20:46
> `++` implies it's an improved version (and even though C was better than C++)

it implies a successor, which is what it is.

Call it whatever you will, but I actually want to hear how this is "problematic". Because I suspect the issue is much more a personal dislike for the license author than anything else and I disagree with strategy of making vague accusations and then weasel out that's being employed here.

**Comment by ProGamerGov** [comment] 2022-11-14 21:54
Name-wise, it might be good idea to try to follow the current OpenRail naming convention:

https://www.licenses.ai/ai-licenses

https://www.licenses.ai/blog/2022/8/18/naming-convention-of-responsible-ai-licenses

**Comment by CarlosMFerr** [comment] 2022-11-16 09:15
Agree with @julien-c on the name, it gives the user a clear idea upfront of what they are getting with the license `no-updates-required-openrail-m` . @yk  as suggested by @ProGamerGov and following OpenRAIL naming convention, it should be at least: `++-openrail-m` (++ OpenRAIL-M), otherwise, OpenRAIL++ would be confusing to users, as they would not know whether t is a license for the model, data, source, app...

**Comment by julien-c** [comment] 2022-11-16 11:17
For now we did add it as `Open Rail++-M License` in https://github.com/huggingface/hub-docs/commit/5ee84833d14e611aa2a1354c62ed306052db5897

we can always update in the future if needed

Screenshot of repo license picker:

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/326577/202166654-ee4f2fa6-be0b-48a6-a64b-dc5538a97e81.png">

**Comment by julien-c** [comment] 2022-11-16 11:17
closing, feel free to reopen if needed!

**Comment by CarlosMFerr** [comment] 2022-11-16 11:40
We should then add a short intro disclaimer for the license: "The OpenRAIL++M license does not include the Preamble nor the model update obligations present in clause 7 of the CreativeML OpenRAIL-M. Therefore, the license does not require users to use the last updated version of the licensed model. Otherwise, the rest of the license is the same as the CreativeML OpenRAIL-M."

**Comment by CarlosMFerr** [comment] 2022-11-24 09:59
Following my earlier comment, to avoid users' confusion would it make sense to tag it as `blank-openrail++` @yk

**Comment by yk** [comment] 2022-12-01 16:00
totally fine with me, thank you

**Closed** 2023-11-20 22:17 UTC
